// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SvgViewer
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPackageString = "a9123ed1-f591-4e17-af69-03aeb8f8ff53";
        public static Guid guidPackage = new Guid(guidPackageString);

        public const string guidEditorFactoryString = "5253d362-aaab-4a53-a4b6-311e5adebb06";
        public static Guid guidEditorFactory = new Guid(guidEditorFactoryString);

        public const string guidIsSvgFileString = "2edea297-bd0c-4801-9dcd-6003f09bf2e8";
        public static Guid guidIsSvgFile = new Guid(guidIsSvgFileString);

        public const string guidCommandsString = "938e8e68-9f8b-4ac1-9f4d-df616d08b8d4";
        public static Guid guidCommands = new Guid(guidCommandsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CTXT_VIEW_GROUP = 0x0001;
        public const int VIEW_CODE = 0x0100;
        public const int VIEW_IMAGE = 0x0200;
    }
}